version: '3.6'
services:
  jenkins:
    network_mode: bridge
    image: jenkins/jenkins:lts
#    depends_on:
#      - selenoid
#    links:
#      - selenoid
    ports:
      - "8081:8080"
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/init/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:/opt/selenoid/video"
      - "$PWD:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
    command: ["-conf", "/init/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
  selenoid-ui:
    network_mode: bridge
    image: aerokube/selenoid-ui:latest-release
#    links:
#      - selenoid
    command: ["--selenoid-url", "http://selenoid:4444"]
    ports:
      - "8080:8080"